version: "3.8"

# Load root .env file

services:
  blog-db:
    build: ./database/mongo
    container_name: blog-db
    env_file: .env
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  blog-backend:
    build:
      context: ./backend
    container_name: blog-backend
    env_file: .env
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      MONGO_URI: ${MONGO_URI}
    depends_on:
      blog-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  blog-frontend:
    build:
      context: ./frontend/client
    container_name: blog-frontend
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:3001" #host:container
    environment:
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    depends_on:
      blog-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongo-data:























